# Generated by Django 4.2.27 on 2026-01-26 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='hora_entrega',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
