# Generated by Django 4.2.27 on 2026-02-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actividad_hora_entrega'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupodocentemateria',
            unique_together={('grupo', 'materia')},
        ),
    ]
