# Generated by Django 6.0.3 on 2026-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grupodocentemateria_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodocentemateria',
            name='parciales_configurados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcial',
            name='numero_parcial',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='parcial',
            unique_together={('grupo_docente_materia', 'numero_parcial')},
        ),
    ]
