# Generated by Django 6.0.3 on 2026-03-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grupodocentemateria_parciales_configurados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('parcial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parcial')),
            ],
        ),
    ]
