# Generated by Django 4.2.29 on 2026-03-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calificacionparcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='parcial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parcial'),
        ),
    ]
