# Generated by Django 4.2.29 on 2026-03-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alerta_parcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='derivada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerta',
            name='derivada_a',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
