# Generated by Django 4.2.29 on 2026-03-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alerta_derivada_alerta_derivada_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('cerrada', 'Cerrada'), ('derivada_pedagogia', 'Derivada a Pedagogía'), ('derivada_direccion', 'Derivada a Dirección'), ('comentario', 'Comentario')], max_length=30)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
