# Generated by Django 4.2.29 on 2026-03-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seguimientoalerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoalerta',
            name='accion',
            field=models.CharField(choices=[('cerrada', 'Cerrada'), ('derivada_tutor', 'Derivada al Tutor'), ('derivada_pedagogia', 'Derivada a Pedagogía'), ('derivada_psicologia', 'Derivada a Psicología'), ('derivada_direccion', 'Derivada a Dirección'), ('comentario', 'Comentario')], max_length=30),
        ),
    ]
