# Generated by Django 6.0.3 on 2026-04-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alumno_correo_alumno_telefono_notificacion_asunto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_creador', models.CharField(choices=[('Tutor', 'Tutor'), ('Pedagogia', 'Pedagogía'), ('Psicologia', 'Psicología'), ('Director', 'Director')], max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('comentario', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.alerta')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
