# Generated by Django 4.2.29 on 2026-04-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.IntegerField()),
                ('orden', models.IntegerField(default=0)),
                ('parcial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderaciones', to='core.parcial')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'unique_together': {('parcial', 'nombre')},
            },
        ),
    ]
