from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard', views.dashboard),
    path('grupos-alumnos', views.gruposAlumnos),
    path('actividades/', views.actividades),
    path('actividades/<int:id>/detalle', views.detalleActividad),
    path('guardar-entregas/', views.guardar_entregas),
    path('estadisticas', views.estadisticas),
    path('alertas', views.alertas),
    path('sidebar', views.sidebar),
    path('director', views.director, name='director'),
    path('tutor', views.tutor),
    path('pedagogia', views.pedagogia, name='pedagogia'),
    path('director/new_user', views.new_user, name='new_user'),
    path("grupo/nuevo/", views.new_group, name="new_group"),
    path('materia/nueva/', views.new_materia, name='new_materia'),
    path('obtener-alumnos-por-grupo/', views.obtener_alumnos_por_grupo, name='obtener_alumnos_por_grupo'),
    path('guardar-asistencia/', views.guardar_asistencia, name='guardar_asistencia'),
    path('obtener-historial-asistencia/', views.obtener_historial_asistencia, name='obtener_historial_asistencia'),
    path('guardar-comentario/', views.guardar_comentario, name='guardar_comentario'),
    path('alumno/<int:alumno_id>/perfil/', views.perfil_alumno, name='perfil_alumno'),
    path('guardar-parciales/', views.guardar_parciales, name='guardar_parciales'),
    path('guardar-calificaciones/', views.guardar_calificaciones, name='guardar_calificaciones'),
    path('obtener-calificaciones/', views.obtener_calificaciones, name='obtener_calificaciones'),
    path('cuatrimestre/nuevo/', views.new_cuatrimestre, name='new_cuatrimestre'),
    path('director/editar-docente/<int:docente_id>/', views.editar_docente, name='editar_docente'),
    path('asistencia/', views.asistencia, name='asistencia'),
    path('obtener-alertas-grupo/', views.obtener_alertas_grupo, name='obtener_alertas_grupo'),
    path('marcar-alerta-atendida/', views.marcar_alerta_atendida, name='marcar_alerta_atendida'),
    path('cerrar-alerta-tutor/', views.cerrar_alerta_tutor, name='cerrar_alerta_tutor'),
    path('derivar-alerta/', views.derivar_alerta, name='derivar_alerta'),
    path('cerrar-alerta-pedagogia/', views.cerrar_alerta_pedagogia, name='cerrar_alerta_pedagogia'),
    path('derivar-alerta-pedagogia/', views.derivar_alerta_pedagogia, name='derivar_alerta_pedagogia'),
    path('cerrar-alerta-psicologia/', views.cerrar_alerta_psicologia, name='cerrar_alerta_psicologia'),
    path('derivar-alerta-psicologia/', views.derivar_alerta_psicologia, name='derivar_alerta_psicologia'),
    path('psicologia', views.psicologia, name='psicologia'),
    path('director/alertas/',            views.director_alertas_view,           name='director_alertas'),
    path('director/alertas/direccion/',  views.director_alertas_direccion_view, name='director_alertas_direccion'),
    path('cerrar-alerta-direccion/',     views.cerrar_alerta_direccion,         name='cerrar_alerta_direccion'),
    path('derivar-alerta-direccion/',    views.derivar_alerta_direccion,        name='derivar_alerta_direccion'),


    path('actividades/', views.actividades),
    path('actividades/<int:id>/detalle/', views.detalleActividad, name='detalle_actividad'),
    path('guardar-entregas/', views.guardar_entregas),
    path('actividades/estadisticas/', views.estadisticas_actividades, name='estadisticas_actividades'),

# ========== RUTAS DE QR ==========
    path('api/login/', views.api_login, name='api_login'),
    path('generar-qr/', views.generar_qr, name='generar_qr'),
    path('ver_asistencias/', views.ver_asistencias, name='ver_asistencias'),
    path('api/materias-por-grupo/<int:grupo_id>/', views.api_materias_por_grupo, name='api_materias_por_grupo'),
    path('api/generar-qr/', views.api_generar_qr, name='api_generar_qr'),
    path('api/validar-qr/', views.api_validar_qr, name='api_validar_qr'),
    path('api/validar-qr-alumno/', views.api_validar_qr_alumno, name='api_validar_qr_alumno'),
    path('api/registrar-asistencia-qr/', views.api_registrar_asistencia_qr, name='api_registrar_asistencia_qr'),
    path('obtener-asistencias-por-grupo/', views.obtener_asistencias_por_grupo, name='obtener_asistencias_por_grupo'),
    path('api/filtrar-asistencias/', views.api_filtrar_asistencias, name='api_filtrar_asistencias'),
]